// Generated by CoffeeScript 1.3.3
(function() {
  var Game, GameCore, cookie, timers,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  GameCore = require('./game.core');

  cookie = require('cookie');

  timers = require('timers');

  module.exports = Game = (function(_super) {

    __extends(Game, _super);

    function Game() {
      var initPos;
      Game.__super__.constructor.call(this);
      this.ballPosition = [this.canvasWidth / 2, this.canvasHeight / 2];
      this.ball_v = 200;
      this.dt = 20;
      this.dt_in_sec = this.dt / 1000;
      this.gamers = {};
      initPos = this.canvasHeight / 2 - 40;
      this.yPositions = [initPos - this.racketHeight, initPos + this.racketHeight];
      this.xOffset = 20;
      this.scores = [0, 0];
      this.count = 0;
      this.startLoop();
    }

    Game.prototype.addGamer = function(sid, socket, side) {
      this.gamers[sid] = {
        socket: socket,
        state: 0,
        side: side,
        pos: this.yPositions[side]
      };
      return this.tellSide(sid);
    };

    Game.prototype.tellSide = function(sid) {
      return this.gamers[sid].socket.emit('joined', this.gamers[sid].side);
    };

    Game.prototype.sendMove = function(sid) {
      return this.gamers[sid].socket.emit('move', {
        positions: this.yPositions,
        ballPosition: this.ballPosition
      });
    };

    Game.prototype.sendMoveAll = function() {
      var sid, _results;
      _results = [];
      for (sid in this.gamers) {
        _results.push(this.sendMove(sid));
      }
      return _results;
    };

    Game.prototype.sendScore = function(sid) {
      return this.gamers[sid].socket.emit('score', {
        scores: this.scores
      });
    };

    Game.prototype.sendScoreAll = function() {
      var sid, _results;
      _results = [];
      for (sid in this.gamers) {
        _results.push(this.sendScore(sid));
      }
      return _results;
    };

    Game.prototype.setState = function(sid, state) {
      return this.gamers[sid].state = state;
    };

    Game.prototype.detectMove = function() {
      var gamer, sid, _ref, _results;
      _ref = this.gamers;
      _results = [];
      for (sid in _ref) {
        gamer = _ref[sid];
        if (gamer.state === -1) {
          gamer.pos -= this.racketStep;
        } else if (gamer.state === 1) {
          gamer.pos += this.racketStep;
        }
        if (gamer.pos < 0) {
          gamer.pos = 0;
        }
        if (gamer.pos > this.canvasHeight - this.racketHeight) {
          gamer.pos = this.canvasHeight - this.racketHeight;
        }
        _results.push(this.yPositions[gamer.side] = gamer.pos);
      }
      return _results;
    };

    Game.prototype.detectBallMove = function() {
      var ballInRacket, ds;
      ds = this.ball_v * this.dt_in_sec;
      this.ballPosition[0] += Math.round(ds * Math.cos(this.angle));
      this.ballPosition[1] += Math.round(ds * Math.sin(this.angle));
      if (this.ballPosition[0] < 0) {
        this.ballPosition[0] = 0;
        this.angle = Math.PI - this.angle;
        return;
      }
      if (this.ballPosition[0] > this.canvasWidth - this.ballSize) {
        this.ballPosition[0] = this.canvasWidth - this.ballSize;
        this.angle = Math.PI - this.angle;
        return;
      }
      if (this.ballPosition[1] < 0) {
        this.ballPosition[1] = 0;
        this.angle = -this.angle;
        return;
      }
      if (this.ballPosition[1] > this.canvasHeight - this.ballSize) {
        this.ballPosition[1] = this.canvasHeight - this.ballSize;
        this.angle = -this.angle;
        return;
      }
      ballInRacket = this.ballPosition[1] >= this.yPositions[0] && this.ballPosition[1] <= this.yPositions[0] + this.racketHeight;
      if (this.ballPosition[0] < this.xOffset && ballInRacket) {
        this.ballPosition[0] = this.xOffset;
        this.angle = Math.PI - this.angle;
        return;
      }
      ballInRacket = this.ballPosition[1] >= this.yPositions[1] && this.ballPosition[1] <= this.yPositions[1] + this.racketHeight;
      if (this.ballPosition[0] > this.canvasWidth - this.xOffset && ballInRacket) {
        this.ballPosition[0] = this.canvasWidth - this.xOffset - this.ballSize;
        this.angle = Math.PI - this.angle;
      }
    };

    Game.prototype.startLoop = function() {
      var _this = this;
      console.log('loop started');
      return this.loop = timers.setInterval(function() {
        return _this.gameStep();
      }, this.dt);
    };

    Game.prototype.endLoop = function() {
      return timers.clearInterval(this.loop);
    };

    Game.prototype.gameStep = function() {
      this.detectMove();
      this.detectBallMove();
      this.sendMoveAll();
      return this.sendScoreAll();
    };

    Game.prototype.oneQuitted = function(sidQuit) {
      var gamer, sid, _ref, _results;
      delete this.gamers[sidQuit];
      _ref = this.gamers;
      _results = [];
      for (sid in _ref) {
        gamer = _ref[sid];
        if (sidQuit !== sid) {
          _results.push(gamer.socket.emit('quit', sid));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Game.prototype.connect = function(socket) {
      var sid,
        _this = this;
      sid = cookie.parse(socket.handshake.headers.cookie)['connect.sid'];
      console.log("Have a connection: " + sid + " (socket id: " + socket.id + ")");
      socket.on('join', function(data) {
        if (sid in _this.gamers) {
          _this.tellSide(sid);
          _this.sendMove(sid);
          return;
        }
        if (_this.count === 2) {
          socket.emit('busy');
          return;
        }
        console.log("I can has join: " + sid);
        _this.addGamer(sid, socket, _this.count);
        _this.sendMove(sid);
        _this.count++;
        if (_this.count > 0) {
          return _this.startLoop;
        }
      });
      socket.on('state', function(data) {
        console.log("Player " + data.side + " moving " + data.state);
        return _this.setState(sid, data.state);
      });
      return socket.on('disconnect', function() {
        if (!(sid in _this.gamers && _this.gamers[sid].socket.id === socket.id)) {
          return;
        }
        console.log("Disconnecting: " + sid);
        _this.oneQuitted(sid);
        _this.count--;
        if (_this.count === 0) {
          return _this.endLoop;
        }
      });
    };

    return Game;

  })(GameCore);

}).call(this);
