// Generated by CoffeeScript 1.3.3
(function() {
  var GameCore;

  GameCore = (function() {

    function GameCore() {
      this.canvasWidth = 780;
      this.canvasHeight = 440;
      this.xOffset = 20;
      this.racketHeight = 55;
      this.racketWidth = 10;
      this.racketStep = 10;
      this.ballSize = 8;
      this.ballPosition = [this.canvasWidth / 2 - this.ballSize / 2, this.canvasHeight / 2 - this.ballSize / 2];
      this.angle = (20 + Math.random() * 50) * Math.PI / 180;
      this.ballV = 200;
      this.dt = 20;
      this.dtInSec = this.dt / 1000;
      this.dirUp = -1;
      this.dirIdle = 0;
      this.dirDown = 1;
    }

    GameCore.prototype.moveRacket = function(state, pos) {
      var newPos;
      newPos = state === this.dirUp ? pos - this.racketStep : state === this.dirDown ? pos + this.racketStep : pos;
      if (newPos < 0) {
        newPos = 0;
      }
      if (newPos > this.canvasHeight - this.racketHeight) {
        newPos = this.canvasHeight - this.racketHeight;
      }
      return newPos;
    };

    GameCore.prototype.moveBall = function() {
      var ds;
      ds = this.ballV * this.dtInSec;
      this.ballPosition[0] += Math.round(ds * Math.cos(this.angle));
      return this.ballPosition[1] += Math.round(ds * Math.sin(this.angle));
    };

    GameCore.prototype.checkBallCollision = function() {
      console.log("Ball collision: " + this.ballPosition);
      if (this.ballPosition[1] < 0) {
        this.ballPosition[1] = 0;
        this.angle = -this.angle;
        console.log("Ball collision <0: " + this.ballPosition);
        return;
      }
      if (this.ballPosition[1] > this.canvasHeight - this.ballSize) {
        this.ballPosition[1] = this.canvasHeight - this.ballSize;
        this.angle = -this.angle;
        console.log("Ball collision >height: " + this.ballPosition);
        return;
      }
      if (this.ballPosition[0] <= this.xOffset) {
        if (this.ballPosition[1] >= this.yPositions[0] && this.ballPosition[1] <= this.yPositions[0] + this.racketHeight - this.ballSize) {
          this.ballPosition[0] = this.xOffset;
          this.angle = Math.PI - this.angle;
          console.log("Ball collision <xoffset: " + this.ballPosition);
          return;
        }
      }
      if (this.ballPosition[0] >= this.canvasWidth - this.xOffset - this.ballSize) {
        if (this.ballPosition[1] >= this.yPositions[1] && this.ballPosition[1] <= this.yPositions[1] + this.racketHeight - this.ballSize) {
          this.ballPosition[0] = this.canvasWidth - this.xOffset - this.ballSize;
          this.angle = Math.PI - this.angle;
          console.log("Ball collision >width: " + this.ballPosition);
        }
      }
    };

    return GameCore;

  })();

  if (typeof module === 'undefined') {
    window.GameCore = GameCore;
  } else {
    module.exports = GameCore;
  }

}).call(this);
