# Here is all our socket machimery.
# We have server events:
# - join - user joins the game
# - state - user updates his position
# - disconnect - user disconnects
# And we have client events, generated by server:
# - joined - tell him about success join and which side he will be playing (left or right for now)
# - state - update his and enemies position
# - quit - some user quitted

class Gamer
  constructor: (@socket) ->
  yourSide: (@side = 0) ->
    @socket.emit 'joined', @side
  heMoved: (who, where) ->
    @socket.emit 'state', where
  heQuitted: (who) ->
    console.log 'who=' + who
    @socket.emit 'quit', who

module.exports = Gamer