#!/bin/sh

echo 'COMPILING'

coffee -c app.coffee             &&
coffee -c routes.coffee          &&
cd game                          &&
coffee -c game.core.coffee       &&
coffee -c game.coffee            &&
coffee -c pongServer.coffee      &&
cd ../public/javascripts         &&
coffee -cj pong.js animation.coffee ../../game/game.core.coffee pong.coffee

