// Generated by CoffeeScript 1.3.3
(function() {
  var compileCoffee, exec, fs, output, sys;

  sys = require('util');

  exec = require('child_process').exec;

  fs = require('fs');

  exports.precompile = function(dir) {
    console.log("" + dir);
    return fs.readdir(dir, function(err, files) {
      var file, _i, _len, _results;
      if (err != null) {
        console.log("Error: " + err);
      }
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        if (file.match(/.coffee$/)) {
          _results.push(compileCoffee(dir + '/' + file));
        }
      }
      return _results;
    });
  };

  compileCoffee = function(file) {
    return exec("coffee -c " + file, output);
  };

  output = function(err, stdout, stderr) {
    return sys.puts(stdout);
  };

}).call(this);
